# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-29 07:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVisual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Upload Video')),
                ('thumbnail_image', models.ImageField(blank=True, help_text='Video Thumbnail Image', null=True, upload_to='pic_folder/')),
                ('path', models.TextField(blank=True, help_text='Embed Link for youtube or any link', null=True)),
                ('author', models.CharField(blank=True, help_text='Content Owner', max_length=250, null=True)),
                ('category', models.CharField(choices=[('Podcast', 'Podcast'), ('Video', 'Video')], max_length=100)),
                ('published', models.BooleanField(default=False)),
                ('payment_status', models.CharField(choices=[('FREE', 'free'), ('PREMIUM', 'paid')], default='free', help_text='Payment Required', max_length=100, verbose_name='Payment Required?')),
                ('description', djangocms_text_ckeditor.fields.HTMLField(default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videouser_manager', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Content Manager',
                'verbose_name_plural': 'Video Content Manager',
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_category_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
            },
        ),
        migrations.CreateModel(
            name='SubDocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sub_category_user', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_category', to='knowledge_center.DocumentCategory')),
            ],
            options={
                'verbose_name': 'Document Sub Category',
                'verbose_name_plural': 'Document Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='TextCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('published', models.BooleanField(default=False)),
                ('author', models.CharField(blank=True, help_text='Content Owner', max_length=250, null=True)),
                ('description', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('FREE', 'free'), ('PREMIUM', 'paid')], help_text='Payment Required', max_length=100, verbose_name='Payment Required?')),
                ('file_upload', models.FileField(blank=True, help_text='Upload an File', null=True, upload_to='pic_folder/')),
                ('external_url', models.CharField(blank=True, help_text='external_url', max_length=100, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_center.DocumentCategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_center.SubDocumentCategory')),
            ],
            options={
                'verbose_name': 'Document / Report Manager',
                'verbose_name_plural': 'Documents / Reports Manager',
            },
        ),
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_category_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Category',
                'verbose_name_plural': 'Video Categories',
            },
        ),
        migrations.AddField(
            model_name='audiovisual',
            name='sub_category',
            field=models.ForeignKey(help_text='Type of Video', null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge_center.VideoCategory'),
        ),
    ]
